name: Test PicoDeprecated pull request

on:
    pull_request: {}

jobs:
    test:
        name: Test PicoDeprecated
        uses: ./.github/workflows/test.yml

    bouncer:
        name: Bouncer

        needs: test
        if: ${{ always() }}

        runs-on: ubuntu-latest
        permissions: {}

        steps:
            - name: Check build matrix status
              if: ${{ needs.test.result != 'success' }}
              run: |
                  :
                  echo "Some tests of PicoDeprecated failed." >&2
                  echo "Please check the GitHub workflow logs for details." >&2
                  exit 1
